@Host = http://localhost:5185

### 1. GET ALL CUSTOMERS
GET {{Host}}/api/v1/customer

### 2. CREATE A NEW CUSTOMER
POST {{Host}}/api/v1/customer
Content-Type: application/json


### 3. UPDATE CUSTOMER 1
PUT {{Host}}/api/v1/customer/1
Content-Type: application/json



### 4. DELETE CUSTOMER 2
DELETE {{Host}}/api/v1/customer/2